import { moderateScale as ms, width } from '@/constants';
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    paddingBottom: ms(16),
  },
  astro: {
    width: ms(88),
    height: ms(88),
    position: 'absolute',
    top: ms(128),
  },
  topLeftBar: {
    width: '100%',
    alignItems: 'flex-start',
    paddingHorizontal: ms(14),
    marginTop: ms(4),
  },
  backButton: {
    width: ms(108),
    height: ms(42),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: ms(8),
  },
  nameStack: {
    width: '100%',
    alignItems: 'center',
    marginTop: ms(8),
  },
  headerPanel: {
    width: width * 0.9,
    height: ms(102),
    paddingTop: ms(28),
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText: {
    color: 'white',
    fontFamily: 'Pixellari',
    textAlign: 'center',
    fontSize: ms(28),
  },
  buttonText: {
    color: 'white',
    fontFamily: 'Pixellari',
    textAlign: 'center',
    fontSize: ms(14),
  },
  namePanel: {
    width: width * 0.9,
    minHeight: ms(146),
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: ms(28),
    marginTop: -4,
    gap: ms(12),
  },
  nameActionsRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: ms(2),
  },
  panelTitle: {
    color: 'white',
    fontFamily: 'Pixellari',
    textAlign: 'center',
    fontSize: ms(20),
  },
  muteButton: {
    width: ms(64),
    height: ms(42),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: ms(8),
  },
  muteIcon: {
    width: ms(16),
    height: ms(16),
    tintColor: 'white',
  },
  changeNameInput: {
    backgroundColor: 'rgba(0,0,0,0.35)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
    width: '100%',
    height: ms(40),
    paddingHorizontal: ms(12),
    borderRadius: ms(6),
    color: 'white',
    fontFamily: 'Pixellari',
    fontSize: ms(16),
    textAlign: 'center',
  },
  clearButton: {
    width: width * 0.48,
    height: ms(42),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: ms(10),
  },
  scoreboardPanel: {
    width: width * 0.9,
    minHeight: ms(368),
    alignItems: 'center',
    padding: ms(28),
    paddingTop: ms(38),
    gap: ms(10),
  },
  scoreboardBody: {
    width: '100%',
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.25)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
    borderRadius: ms(8),
    paddingVertical: ms(8),
    paddingHorizontal: ms(10),
    minHeight: ms(258),
    maxHeight: ms(258),
  },
  scoreHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.25)',
    paddingBottom: ms(6),
    marginBottom: ms(2),
  },
  scoreHeaderMetaText: {
    color: 'rgba(255,255,255,0.85)',
    fontFamily: 'Pixellari',
    fontSize: ms(11),
    minWidth: ms(36),
    textAlign: 'center',
  },
  scoreHeaderNameText: {
    color: 'rgba(255,255,255,0.85)',
    fontFamily: 'Pixellari',
    fontSize: ms(11),
    flex: 1,
    textAlign: 'center',
  },
  scoreboardLoadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scoreboardList: {
    width: '100%',
    flex: 1,
  },
  scoreboardListContent: {
    paddingBottom: ms(8),
  },
  inlineLoader: {
    paddingVertical: ms(6),
  },
  scoreboardPlaceholderText: {
    color: 'white',
    fontFamily: 'Pixellari',
    fontSize: ms(12),
    textAlign: 'center',
    opacity: 0.75,
    paddingVertical: ms(8),
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: ms(4),
    gap: ms(8),
  },
  scoreMetaText: {
    color: 'white',
    fontFamily: 'Pixellari',
    fontSize: ms(20),
    minWidth: ms(36),
    textAlign: 'center',
  },
  scoreNameText: {
    color: 'white',
    fontFamily: 'Pixellari',
    fontSize: ms(20),
    flex: 1,
    textAlign: 'center',
  },
  playerScoreText: {
    color: '#FFE15A',
  },
  creditPanel: {
    width: width * 0.9,
    minHeight: ms(84),
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: ms(12),
    marginTop: ms(8),
  },
  creditsTitle: {
    color: 'white',
    fontFamily: 'Pixellari',
    fontSize: ms(14),
    opacity: 0.85,
  },
  creditsName: {
    color: 'white',
    fontFamily: 'Pixellari',
    fontSize: ms(16),
    marginTop: ms(4),
  },
});

export default styles;
