/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/game`; params?: Router.UnknownInputParams; } | { pathname: `/screens/game/styles`; params?: Router.UnknownInputParams; } | { pathname: `/screens/home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/home/styles`; params?: Router.UnknownInputParams; } | { pathname: `/screens/settings`; params?: Router.UnknownInputParams; } | { pathname: `/screens/settings/styles`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/game`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/game/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/home`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/home/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/settings/styles`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/screens/game${`?${string}` | `#${string}` | ''}` | `/screens/game/styles${`?${string}` | `#${string}` | ''}` | `/screens/home${`?${string}` | `#${string}` | ''}` | `/screens/home/styles${`?${string}` | `#${string}` | ''}` | `/screens/settings${`?${string}` | `#${string}` | ''}` | `/screens/settings/styles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/game`; params?: Router.UnknownInputParams; } | { pathname: `/screens/game/styles`; params?: Router.UnknownInputParams; } | { pathname: `/screens/home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/home/styles`; params?: Router.UnknownInputParams; } | { pathname: `/screens/settings`; params?: Router.UnknownInputParams; } | { pathname: `/screens/settings/styles`; params?: Router.UnknownInputParams; };
    }
  }
}
